# Generated by Django 6.0.6 on 2026-06-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studyfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyfile',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyfile',
            name='summary_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
